name:                PBEM-Helper
version:             0.1.0.0
github:              "githubuser/PBEM-Helper"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/PBEM-Helper#readme>

dependencies:
- base >= 4.7 && < 5
- base >= 4.7 && < 5
- zip-archive >= 0.3.3
- bytestring >= 0.10.8.2
- binary >= 0.8.5.1
- ConfigFile >= 1
- directory >= 1.3.1.5
- MissingH >= 1.3.0.1
- strict >= 0.3.2

library:
  source-dirs: src

executables:
  PBEM-Helper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PBEM-Helper

tests:
  PBEM-Helper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PBEM-Helper
